PackRat-AI/PackRat

- client/components/feed/Feed.js
- client/components/map/MapContainer.native.js
- client/components/pack_table/Table.js
- client/utils/mapFunctions.js
> Mikibo fix rnmapbox integration

- client/components/details/index.js
- client/components/trip/TripDateRange.js
- client/components/trip/createTrip.js
- client/components/trip/createTripModal.js
- client/package.json
- server/controllers/tripController.js
added date range picker on create trip page. for date range picker using 'react-native-paper-dates'  package.
Date Range picker:
> added date range picker in trip create page

- client/components/feed/FeedCard.js
- client/store/packsStore.js
- server/controllers/packController.js
- server/middleware/validators/packRoutesValidator.js
- server/routes/packRoutes.js
added copying icon that is pressable and some redux stats and some backend routes and controllers for handling of duplicating pack item
> Copy public pack

- client/components/map/MapPreview.js
- client/components/map/NativeMap.native.js
- client/components/map/WebMap.web.js
> add static map image preview

- client/app/drawer/index.js
- client/components/DuplicateIcon/index.js
- client/components/feed/Feed.js
Hi Andrew, Kindly review this PR for "Feed Component Crashing on Native" fix
> Fixed Feed Component Crashing on Native

- client/components/dashboard/HeroBanner.js
- client/components/trip/TripDetails.js
- client/components/trip/createTripModal.js
- client/store/destinationStore.js
- client/store/tripsStore.js
- server/controllers/getOsmController.js
- server/controllers/tripController.js
- server/models/geojsonModel.js
- server/models/tripModel.js
- server/workers/osmWorker.js
Save geojson to db directly instead of modelling osm types. This will simplify lots of things and fix lots of the issues faced with saving osm while also preventing duplication.
> Mikibo save geojson for destination

- package.json
- Add  "start:prod": "npm run start:prod --prefix server",
> Add - start:prod script to package.json

- client/components/carousel/ScrollButton.js
- client/components/carousel/index.js
Fixed crash due to merging code.
> fixing issue with merge

- client/components/card/index.tsx
Uses #487 as base branch, so the PR diff against `andrew_testing` will show changes that are already present there.
Please notify me if you want me to group the changes for all views in a single PR.
> Refactor Card to use our tamagui wrapper instead of native-base

- client/components/landing_page/index.tsx
- client/screens/dashboard/index.tsx
- packages/ui/src/XStack/index.tsx
- packages/ui/src/YStack/index.tsx
- packages/ui/src/index.tsx
Converting some of the native-base components:
Text => RText
View => RStack
VStack => YStack
HStack => XStack
ScrollView => RScrollView
Implementation is done in:
- landing_page
- dashboard
new file created in package/ui:
- XStack
- YStack
> Converting native-base to Tamagui

- server/package.json
- server/src/controllers/openAi/getAIResponse.ts
- server/src/controllers/openAi/langchain/index.ts
- yarn.lock
- conversion of openai library to langchain
- converted getAIResponseService.ts to langchain/index.ts for making use of langchain in new versions
/claim #502
> Langchain Integration

- client/app/(app)/items/index.tsx
- client/screens/items/index.tsx
Resolves the data.globalItems is undefined error when clicking items in nav bar.
> Items screen bug

- client/components/ScoreContainer.tsx
- client/hooks/score/index.ts
- client/hooks/score/useGradingPie.ts
- client/hooks/score/useScoreData.ts
- client/hooks/score/useScoreProgress.ts
refactored `ScoreContainer.tsx` with custom hooks.
> refactor `ScoreContainer.tsx`

- server/src/tests/routes/user/index.test.ts
Implemented basic test cases for user routes. This PR is still in progress as all TRPC routes are not covered yet.
No negative flows or values are considered in test cases yet. Also, all test cases are in a single file to use common user data across all test suits. Later, it can be converted to a common global setup for the necessary context data.
> created basic test cases without negative values for user routes

- packages/app/components/navigation/NavigationItem.tsx
**Description**:
Navigation alignment is not correct
**Screenshot**:
> fix: navigation alignment

- packages/app/components/itemtable/itemTable.tsx
- packages/app/components/itemtable/itemsTable.style.ts
- packages/app/components/paginationChooseLimit/index.tsx
- packages/app/screens/items/index.tsx
- Errors Fixed
- - Text strings must be rendered within a <Text> component (Item component)
- Design Fixed
- - Pagination
- - Table
- - Dropdown
- - Table ScrollView
> fix: items design and errors

- apps/next/package.json
- packages/app/components/feed/FeedSearchFilter.tsx
- packages/app/components/pack/PackDetails.tsx
- packages/app/components/user/UserDataContainer.tsx
- packages/app/screens/user/ProfileContainer.tsx
- feed fixed
- search bar fixed
- quick actions fixed
on native side
> fix: feed quick actions and search bar

- packages/app/components/feed/FeedCard.tsx
- packages/app/components/item/AddItem.tsx
- packages/app/components/item/ItemForm.tsx
- packages/app/components/user/UserDataCard.tsx
- packages/app/components/user/UserDataContainer.tsx
- packages/app/hooks/favorites/useAddFavorite.ts
- packages/app/hooks/packs/useAddPackItem.ts
- packages/app/hooks/score/useScoreData.ts
- packages/app/screens/feed/Feed.tsx
- server/migrations/0000_exotic_the_enforcers.sql
- server/migrations/meta/0000_snapshot.json
- server/migrations/meta/_journal.json
- server/src/db/schema.ts
- server/src/drizzle/methods/User.ts
- server/src/drizzle/methods/pack.ts
- server/src/services/favorite/getUserFavoritesService.ts
- server/src/services/pack/getPackByIdService.ts
- server/src/services/pack/getPackService.ts
- server/src/services/pack/getPublicPacksService.ts
- server/src/utils/pack.ts
There are still some problems when sorting packs by items.
> Resolve frontend integration problems for pack related routes

- packages/app/screens/RegisterScreen.tsx
Previously the register screen did not have a scrollview. Now I added
> fix: Add scrollview to register screen

- packages/app/components/feed/FeedCard.tsx
- packages/ui/src/RContextMenu/index.tsx
- packages/ui/src/index.tsx
> add zeego context menu to feed cards

- apps/expo/app/(app)/(drawer)/(tabs)/search.tsx
- packages/app/components/PlacesAutocomplete/PlacesAutocomplete.tsx
- packages/app/components/SearchInput/SearchInput.tsx
- packages/app/components/dashboard/HeroBanner.tsx
- packages/app/components/navigation/Tabs.tsx
Redesigned search on native.
Closes #707
> Redesign search for native

- packages/app/components/TripCard.tsx
- packages/app/components/card/CustomCard.tsx
- packages/app/components/details/index.tsx
- packages/app/screens/trip/TripDetails.tsx
> [#737] Fix trip details screen UI

- apps/expo/app/(app)/(drawer)/(tabs)/(stack)/_layout.tsx
- apps/next/pages/_app.tsx
- apps/tauri/pages/_app.tsx
- packages/app/components/PackOptions/index.tsx
- packages/app/components/dashboard/HeroBanner.tsx
- packages/app/components/feed/FeedSearchFilter.tsx
- packages/app/components/navigation/Tabs.tsx
- packages/app/screens/dashboard/index.tsx
- packages/app/screens/feed/Feed.tsx
- packages/app/screens/user/ProfileContainer.tsx
> redesign stack headers and fix tabbar blur

- packages/app/components/feed/FeedCard.tsx
- packages/app/hooks/packs/useDeletePack.ts
> Resolve Issues

- packages/app/components/trip/createTripModal.tsx
> [#785] fix trips isPublic field

- packages/app/components/pack/AddPack.tsx
Fixed "Add pack" button not working on native side.
> fix submit button not working when creating pack on native

- packages/app/components/navigation/NavigationList.tsx
- packages/app/hooks/common/useIsMobileView/index.ts
> [#769] Fix Menu Visibility on Mobile Web

- packages/app/components/feed/FeedCard.tsx
I have made a correction to my last PR
> fix for pack owner profile access done

- packages/app/components/pack/AddItemModal.tsx
- packages/ui/src/modal/BaseModal.tsx
Add item modal (in create pack) closes on submit.
> Add item modal closes on submit

- packages/ui/src/modal/BaseModal.tsx
fixes add item modal ui on native
> give max-width style to dialog content for native

- packages/app/components/SearchInput/SearchInput.tsx
- packages/app/components/card/CustomCard.tsx
- packages/app/components/card/CustomCardHeader.tsx
- packages/app/components/itemtable/itemTable.tsx
- packages/app/components/navigation/Navbar/Navbar.tsx
- packages/app/components/pack_table/DeletePackItemModal.tsx
- packages/app/components/pack_table/EditPackItemModal.tsx
- packages/app/components/pack_table/TableItem.tsx
- packages/app/screens/user/Settings.tsx
- packages/ui/src/ZDropdown/index.tsx
> UI update issues on mobile web

- packages/app/components/card/PackCardHeader/PackCardHeader.tsx
- packages/app/components/pack/PackDetails.tsx
Added save pack button and back button to pack.
> Add save pack button and back button to pack

- packages/app/components/card/TripCardHeader/TripCardHeader.tsx
- packages/app/screens/user/Settings.tsx
Add back feature to trip and profile settings.
> Add back feature to trip and profile settings

- packages/app/components/pack/PackDetails.tsx
Fixes pack details not showing on native.
> Fix pack details blank on native

- packages/app/screens/about/AboutContent.tsx
Make about page scrollable on native.
> Make about page scrollable on native

- packages/app/components/card/CustomCardHeader.tsx
- packages/app/components/card/PackCardHeader/PackCardHeader.tsx
- packages/app/components/card/TripCardHeader/TripCardHeader.tsx
- packages/app/screens/user/Settings.tsx
Fix back feature not working on vite.
> fix back feature

- packages/app/components/item/SearchItem/useSearchItem.ts
get packId param from usePackId hook instead of window.location
> get packId param from usePackId hook instead of window.location

- packages/app/components/pack/AddPack.tsx
handle response while creating pack
> handle response while creating pack

- packages/ui/src/ZDropdown/index.tsx
fix pack item dropdown on native
> fix pack item dropdown on native

- packages/app/components/pack_table/DeletePackItemModal.tsx
- packages/app/components/pack_table/EditPackItemModal.tsx
- packages/app/components/pack_table/TableItem.tsx
fix edit and delete options on pack item
> fix edit and delete options on pack item

- packages/app/components/pack_table/TableItem.tsx
Add useEffect hook for closing the edit modal
> Add useEffect hook for closing the edit modal

- packages/app/components/ScoreContainer.tsx
- packages/app/components/carousel/index.tsx
- packages/app/components/feed/FeedCard.tsx
- packages/app/components/trip/createTripModal.tsx
- packages/app/screens/trip/createTrip.tsx
**Fixes**
1.  Arrows in the Create Trip page are working fine now.
2.  "Save" button is more visible now.
> Trip Creation functionality fix

- packages/app/context/FontLoader.tsx
- packages/config/src/index.js
🐛 refactoring env shim due to expo not supporting dynamic env structuring
> 🐛 Debugging expo env error on release config 

- packages/app/components/navigation/Navbar/Navbar.tsx
> Change in color

- packages/app/components/chat/index.tsx
- packages/app/screens/about/AboutContent.tsx
- packages/app/screens/about/about.style.tsx
Remove flatlist inside scrollview in chat and changes in style of about page
> Remove flatlist inside scrollview in chat and about style changes

- packages/app/components/feed/FeedSearchFilter.tsx
- packages/app/components/pack/AddPack.tsx
- packages/app/components/pack_table/packtable.style.tsx
- packages/app/components/user/UserDetailList.tsx
Changes in style in FeedSearchFilter, AddPack,  packtable.style and  UserDetailList
> Changes in style

- packages/app/components/SearchInput/SearchInput.tsx
- packages/app/components/card/LargeCard.tsx
- packages/app/components/destination/index.tsx
- packages/app/components/weather/WeatherCard.tsx
- packages/app/utils/mapFunctions.ts
Changes in style of largecard and weathercard
> Changes in style of largecard and weathercard

- packages/app/components/card/CustomCard.tsx
- packages/app/hooks/feed/publicFeed.ts
Enable pull to refresh in feed and assign a number to zindex instead of string in customcard
> Enable pull to refresh in feed

- packages/app/components/card/CustomCardHeader.tsx
- packages/app/components/card/PackCardHeader/PackCardHeader.tsx
- packages/app/components/pack/CopyPackModal.tsx
- packages/ui/src/EditableText/useEditableText.ts
- packages/ui/src/ZDropdown/index.tsx
onClose implementation in copy pack modal
> onClose implementation in copy pack modal

- packages/app/screens/user/Settings.tsx
@EngrAJ8888 last item of " Android App Issues: Pack Creation/Profile/Feed #1014 " is fixed in this pull request. Please Check.
> Add back feature

- packages/app/constants/api.ts
- packages/app/screens/LoginScreen.tsx
- packages/app/screens/RegisterScreen.tsx
- packages/ui/src/Bento/forms/layouts/SignInScreen.tsx
- packages/ui/src/Bento/forms/layouts/SignUpScreen.tsx
@andrew-bierman it's done now. please check it out
> Login and Signup UI Changed

- packages/app/components/feed/FeedSearchFilter.tsx
> Fix profile UI broken on Native

- apps/expo/metro.config.js
- apps/expo/tsconfig.json
- server/tsconfig.json
This pr fix validation workspace hot reloading on server and expo application.
> Fix validation hot reloading on native and server apps

- .github/actions/setup-wrangler-toml/action.yml
- .github/workflows/backend-preview.yml
- .github/workflows/backend.yml
- server/package.json
- server/src/index.ts
- yarn.lock
I made sure it worked before creating the pr: [Here is the run :point_down: ](https://github.com/andrew-bierman/PackRat/actions/runs/10765967688)
Additional Information:
- All sensitives variables are removed from `wrangler.toml`
- These sensitives variables are uploaded as secrets
- The generated wrangler.toml now contain information of the current environment only
> Automatically deploy backend api based on branch update.

- .github/workflows/eas-cloud.yml
- apps/expo/eas.json
ref: https://docs.expo.dev/build-reference/app-versions/
> Auto increament build version on preview workflow

- packages/validations/src/validations/tripRoutesValidator/tripRoutesValidator.ts
Reverts andrew-bierman/PackRat#1394
> Revert "potential fix/the error doesnt make sense"

- apps/guides/content/posts/beginners-guide-to-seasonal-packing-adapting-to-changing-weather-conditions.mdx
- apps/guides/content/posts/crafting-the-perfect-pack-for-biking-trails.mdx
- apps/guides/content/posts/eco-friendly-upgrades-swapping-out-wasteful-gear.mdx
- apps/guides/content/posts/emergency-pack-essentials-be-prepared-for-the-unexpected.mdx
- apps/guides/content/posts/off-the-grid-adventures-packing-for-remote-destinations.mdx
- apps/guides/content/posts/packing-light-on-a-budget-affordable-solutions-for-weight-management.mdx
- apps/guides/content/posts/smart-layering-how-to-dress-for-any-trail-condition.mdx
- apps/guides/content/posts/tech-savvy-hiking-using-apps-for-efficient-pack-management.mdx
- apps/guides/content/posts/top-10-must-have-gadgets-for-the-modern-outdoor-adventurer.mdx
- apps/guides/content/posts/trail-snacks-that-go-the-distance-long-lasting-energy-boosters.mdx
This PR adds 10 new guide articles focused on topics such as:
- Family-friendly hikes
- Sustainable hiking gear
- Trail nutrition tips
- Packing essentials
- Beginner advice and more
These articles are part of the ongoing content development for the Guides app. Each guide follows the approved format and content guidelines.
Notes
- All articles were pushed last Friday (July 12, 2025).
- Let me know if any adjustments are needed.
> Add 10 New Guide Articles

- apps/expo/package.json
- bun.lock
> Chore:Update/react native keyboard controller

- apps/expo/app/(app)/ai-chat.tsx
> Fix ai suggestion bubble

- apps/expo/features/catalog/lib/cacheCatalogItemImage.ts
> Fix/Patch Image Caching When Adding Catalog Item to Pack 

- apps/expo/app/(app)/ai-chat.tsx
- apps/expo/features/catalog/screens/CatalogItemsScreen.tsx
- apps/expo/lib/hooks/useColorScheme.tsx
Fixes the ai-chat  ui misalignment issue that Jewel reported.
https://github.com/user-attachments/assets/bde0e06f-6fb1-4014-be80-648fe1ecd452
and closes #1469
> Fix/Ui for chat and catalogItemScreen
